### ISSUE TITLE
Empty .trlc files throw error according to TRLC 2.0.0

### ISSUE THREAD

**Issue by DiFerMa** [bmw-software-engineering/trlc#113]
if any .trlc file is created and has no contents following error comes:

`./path/to/empty.trlc:1:1: error: expected keyword package, encountered end-of-file instead
Processed 1 model and 1 requirement files and found 1 error`

**Comment by florianschanda** [comment]
Strictly speaking, the LRM does not allow this. I seem to remember that this used to work though as a special usability allowance.

**Comment by florianschanda** [comment]
My memory was wrong. There was a bug where we'd just crash instead, but now we correctly produce the error message.
