### ISSUE TITLE
change default operation

### ISSUE THREAD

**Issue by florianschanda** [bmw-software-engineering/trlc#54]
Make `-I .` the default mode of operation.

Add new parameter `--no-default-include` or similar to restore the current behaviour.

**Comment by phiwuu** [comment]
How exactly shall the default mode of operation behave?
If all files are treated as `-I`, then how does TRLC know which file to analyze for sure?
Is the idea to treat folders as `-I`, but files as "include for sure"?

**Comment by phiwuu** [comment]
I am closing this ticket, as I don't see the benefit right now.
