### ISSUE TITLE
Requirement "Name_resolution LRM.Sufficiently_Distinct" not met

### ISSUE THREAD

**Issue by christophkloeffel** [bmw-software-engineering/trlc#62]
the following requirement is not met https://github.com/bmw-software-engineering/trlc/blob/adc0cf448e8b4a933d6f2ee6916ad1cd2b5d0bb5/language-reference-manual/lrm.trlc#L1829-L1836

either remove the requirement from the LRM or implement the missing feature

**Comment by florianschanda** [comment]
Good catch, I think. I could have sworn this is implemented but the logical place for it would be in the symbol table. However it is not.

**Comment by florianschanda** [comment]
@phiwuu I think two options make sense:

1. (my preferred) broaden this to cover any and all names, so it would also cover type names, enumeration literals, record fields, etc.
1. remove it

Just doing this for record objects like the manual currently says is both inconsistent and annoying to implement. Do you have a preference?
